name: Run INS Tests
on: [push]
env:
  TLSI_INS_CERTIFICATE_PASSPHRASE: ${{ secrets.TLSI_INS_CERTIFICATE_PASSPHRASE }}
  TLSI_INS_IDAM: ${{ secrets.TLSI_INS_IDAM }}
  TLSI_INS_SOFTWARE_NAME: ${{ secrets.TLSI_INS_SOFTWARE_NAME }}
  TLSI_INS_SOFTWARE_VERSION: ${{ secrets.TLSI_INS_SOFTWARE_VERSION }}
jobs:
  tests:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
      - run: npm install
      - run: npm test src/ins/test/insi-client.test.ts src/ins/test/insi-virtual-mode.test.ts
