name: Run Medimail Tests
on: [push]
env:
  MEDIMAIL_CERTIFICATE_PASSPHRASE: ${{ secrets.MEDIMAIL_CERTIFICATE_PASSPHRASE }}
  MEDIMAIL_ACCOUNT_EMAIL: ${{ secrets.MEDIMAIL_ACCOUNT_EMAIL }}
  MEDIMAIL_TEST_RECIPIENT_EMAIL: ${{ secrets.MEDIMAIL_TEST_RECIPIENT_EMAIL }}
jobs:
  tests:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21'
          cache: 'npm'
      - run: npm install
      - run: npm test src/medimail/test/medimail-client.test.ts
